### ISSUE TITLE
[IMPROVEMENT] Increase Player Acceleration (?)

### ISSUE THREAD

**Issue by roxanneruan** [beanbeanjuice/back-to-the-jungle#128]
## Improvement Description

This depends on how everyone feels about the pace of the player, but I think an acceleration of 0.03 or 0.035 would fit better since our game is supposed to be fast paced. The acceleration of 0.025 feels a little slow at the beginning and takes a while to speed up.

___

## Additional Context
Add any other context or screenshots about the improvement request here.

___

## Checklist

- [ ] I have checked for similar issues.
- [ ] This is an improvement request, not a feature request, bug report, or security vulnerability report.
- [ ] I have assigned myself or someone else to this issue.
- [ ] I have added this issue into the Gantt chart with the issue's creation date as the start date.
- [ ] I will remember to update the Gantt chart with the end date as the completion date for this issue as well as properly filling in the colors.

**Comment by beanbeanjuice** [comment]
I'm okay with this idea, but I think it might be safe to also implement a "maximum velocity" too so that it doesn't go to hyper-speed. When it reaches maximum velocity, then it sets acceleration to 0.
