### ISSUE TITLE
[FEATURE] Initial Shop Menu Design

### ISSUE THREAD

**Issue by beanbeanjuice** [beanbeanjuice/back-to-the-jungle#42]
## Feature Description
Create an initial design for the game over menu. @nwestl should layout the game over menu UI below and the visuals team should design artwork based on the UI layout.

The artwork should be located in `Assets/Resources/UI/Shop/`.

___

## Checklist

- [x] I have checked for similar issues.
- [x] This is a feature request, not an improvement request, bug report, or security vulnerability report.
- [x] I have assigned myself or someone else to this issue.

**Comment by nwestl** [comment]
![image](https://github.com/beanbeanjuice/back-to-the-jungle/assets/131192822/fc8be392-1b04-43cb-8e5c-1c77ac54144c)
